// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
    // MacOS, Windows, Linux not configured...
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // Add databaseURL below
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN0zHSqyutY1LjtgO4igZlezw8p8I_stA',
    appId: '1:380239055049:web:f6dc2371b3ab56ba79e518',
    messagingSenderId: '380239055049',
    projectId: 'pawpal-128f4',
    authDomain: 'pawpal-128f4.firebaseapp.com',
    storageBucket: 'pawpal-128f4.firebasestorage.app',
    databaseURL: 'https://pawpal-128f4-default-rtdb.firebaseio.com', // ← added
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXhhKoeFsGsoPjHAjoh3WL81MPfuyWyW8',
    appId: '1:380239055049:android:5f2f458adff2a74c79e518',
    messagingSenderId: '380239055049',
    projectId: 'pawpal-128f4',
    storageBucket: 'pawpal-128f4.firebasestorage.app',
    databaseURL: 'https://pawpal-128f4-default-rtdb.firebaseio.com', // ← added
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYVQaatnzRW3XIfzsx9BHyaEGeUtSqVcE',
    appId: '1:380239055049:ios:c77d713a6b06728179e518',
    messagingSenderId: '380239055049',
    projectId: 'pawpal-128f4',
    storageBucket: 'pawpal-128f4.firebasestorage.app',
    iosBundleId: 'com.example.pawpal',
    databaseURL: 'https://pawpal-128f4-default-rtdb.firebaseio.com', // ← added
  );
}
